import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {chromium} from 'playwright';
const bundle=await build({stdin:{contents:`
import React from 'react';import{createRoot}from'react-dom/client';import{flushSync}from'react-dom';
import{Checkbox}from'./registry/cojeev/ui/checkbox';import{RadioGroup,RadioGroupItem}from'./registry/cojeev/ui/radio-group';import{Switch}from'./registry/cojeev/ui/switch';
import{setMotionMode,setMotionCategory,setFlowSettings}from'./registry/cojeev/motion/settings';window.enableControls=()=>{setMotionMode('subtle');setFlowSettings({variant:'glide'});setMotionCategory('controls',true);};
const root=createRoot(document.getElementById('root'));window.renderChoice=(appearance='card',controlled=false)=>{window.calls=[];flushSync(()=>root.render(<form key={appearance+controlled}>
<Checkbox appearance={appearance} radius="soft" name="extras" value="notes" defaultChecked="indeterminate" {...(controlled?{checked:false}:{})} onCheckedChange={v=>window.calls.push(v)}>Notes</Checkbox>
<RadioGroup appearance={appearance} pictographic radius="soft" name="mode" defaultValue="a" {...(controlled?{value:'a'}:{})} onValueChange={v=>window.calls.push(v)}><RadioGroupItem value="a">Alpha</RadioGroupItem><RadioGroupItem value="b" disabled>Beta</RadioGroupItem><RadioGroupItem value="c">Gamma</RadioGroupItem></RadioGroup>
{['capsule','rocker','latch'].map(a=><Switch key={a} ref={node=>{if(a==='rocker')window.rocker=node;}} appearance={a} radius="soft" aria-label={a} name={a} value="yes" {...(controlled?{checked:false}:{})} onCheckedChange={v=>window.calls.push(v)}/>)}
<Switch appearance="latch" disabled defaultChecked aria-label="Managed setting" />
</form>));};window.renderChoice();`,loader:'tsx',resolveDir:process.cwd()},bundle:true,write:false,format:'iife',platform:'browser',define:{'process.env.NODE_ENV':'"production"'}});
const browser=await chromium.launch();
const origin=process.env.DOCS_ORIGIN??'http://127.0.0.1:4320';const html=await(await fetch(`${origin}/cojeev-ui/docs/checkbox/`)).text();const links=[...html.matchAll(/href="([^"]+\.css[^\"]*)"/g)].map(match=>match[1]);const css=(await Promise.all(links.map(async href=>(await fetch(new URL(href,origin))).text()))).join('\n');
try{const page=await browser.newPage({reducedMotion:'reduce'});await page.setContent('<div id="root" style="width:360px;padding:20px"></div>');await page.addStyleTag({content:css});await page.addScriptTag({content:bundle.outputFiles[0].text});
const check=page.getByRole('checkbox');assert.equal(await check.getAttribute('data-appearance'),'card','appearance belongs to reusable primitive');assert.equal(await check.getAttribute('aria-checked'),'mixed');await check.click();assert.equal(await check.getAttribute('aria-checked'),'true');await check.press('Space');assert.equal(await check.getAttribute('aria-checked'),'false');
assert.equal(await page.locator('[appearance],[radius]').count(),0,'cosmetic props do not leak to DOM');assert.equal(await check.evaluate(e=>getComputedStyle(e).borderTopLeftRadius),'8px');assert.equal(await page.getByRole('radio',{name:'Alpha'}).evaluate(e=>getComputedStyle(e).borderTopLeftRadius),'8px','radio item inherits group radius');
const radio=page.getByRole('radio',{name:'Alpha'});await radio.focus();await page.evaluate(()=>window.calls=[]);await radio.press('ArrowDown');await page.waitForFunction(()=>document.activeElement?.textContent==='Gamma');assert.equal(await page.getByRole('radio',{name:'Gamma'}).getAttribute('aria-checked'),'true');assert.deepEqual(await page.evaluate(()=>window.calls),['c']);
for(const appearance of ['capsule','rocker','latch']){const toggle=page.getByRole('switch',{name:appearance});assert.equal(await toggle.getAttribute('data-appearance'),appearance);const rect=await toggle.boundingBox();await toggle.click();assert.equal(await toggle.getAttribute('aria-checked'),'true');assert.deepEqual(await toggle.boundingBox(),rect);await toggle.press('Space');assert.equal(await toggle.getAttribute('aria-checked'),'false');assert.equal(await toggle.getAttribute('data-motion-quiet'),'true');}
await check.click();await page.getByRole('switch',{name:'latch'}).click();assert.deepEqual(await page.evaluate(()=>[...new FormData(document.querySelector('form')).entries()]),[['extras','notes'],['mode','c'],['latch','yes']]);
await page.evaluate(()=>window.renderChoice('chip',true));await check.click();assert.equal(await check.getAttribute('aria-checked'),'false');await page.getByRole('switch',{name:'rocker'}).click();assert.equal(await page.getByRole('switch',{name:'rocker'}).getAttribute('aria-checked'),'false');
assert.equal(await page.evaluate(()=>window.rocker===document.querySelector('[aria-label="rocker"]')),true,'forwarded ref remains the native button');assert.equal(await page.getByRole('switch',{name:'Managed setting'}).isDisabled(),true);assert.equal(await page.getByRole('switch',{name:'Managed setting'}).getAttribute('aria-checked'),'true');
await radio.focus();await page.evaluate(()=>window.calls=[]);await radio.press('ArrowDown',{delay:60});assert.deepEqual(await page.evaluate(()=>window.calls),['c'],'controlled refusal still emits only one navigation callback');assert.equal(await radio.getAttribute('aria-checked'),'true');
await page.emulateMedia({reducedMotion:'no-preference'});await page.evaluate(()=>window.enableControls());
for(const appearance of ['capsule','rocker','latch']){const toggle=page.getByRole('switch',{name:appearance});await toggle.scrollIntoViewIfNeeded();const before=await toggle.boundingBox();await page.mouse.move(before.x+before.width/2,before.y+before.height/2);await page.mouse.down();await page.waitForTimeout(200);assert.deepEqual(await toggle.boundingBox(),before,'enabled control motion cannot scale the native hit target');assert.notEqual(await toggle.locator('[data-slot="switch-face"]').evaluate(e=>getComputedStyle(e).transform),'none','decorative face retains real press response');await page.mouse.up();for(let i=0;i<3;i++){await page.mouse.down();await page.waitForTimeout(35);assert.deepEqual(await toggle.boundingBox(),before,'rapid reversal keeps stable target');await page.mouse.up();}assert.ok(before.height>=44);}
await page.evaluate(()=>window.renderChoice('row'));const rows=await page.getByRole('radio').evaluateAll(nodes=>nodes.map(e=>{const b=e.getBoundingClientRect();return {top:b.top,bottom:b.bottom,indicator:getComputedStyle(e.querySelector('[data-slot="radio-group-indicator"]')).position};}));assert.ok(rows[1].top>=rows[0].bottom&&rows[2].top>=rows[1].bottom,'explicit row overrides pictographic columns');assert.ok(rows.every(row=>row.indicator!=='absolute'),'row indicators stay in normal content flow');
console.log('PASS reusable choice appearances, mixed state, Space/pointer, disabled radio skip/exact callback, form values, controlled refusal, stable switch bounds and quiet state');
}finally{await browser.close();}
