import assert from "node:assert/strict";
import { chromium } from "playwright";
import fs from "node:fs/promises";

const base = process.env.POLISH_URL ?? "http://127.0.0.1:4320/cojeev-ui";
const out = "output/playwright/reporting-stack";
await fs.mkdir(out, { recursive: true });
const browser = await chromium.launch();
const attachment = { name: "reference.png", mimeType: "image/png", buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jf3sAAAAASUVORK5CYII=", "base64") };
try {
  for (const width of [1440, 390]) for (const mode of ["light", "dark"]) {
    const context = await browser.newContext({ viewport: { width, height: 960 } });
    await context.route(/https:\/\/(?:us|eu)\.i\.posthog\.com\//, route => route.fulfill({ status: 200, body: "1" }));
    const page = await context.newPage();
    const errors = []; const submissions = [];
    page.on("pageerror", error => errors.push(error.message));
    await page.route("**/v1/reports**", route => { submissions.push(route.request().url()); return route.abort(); });
    await page.addInitScript(mode => localStorage.setItem("cojeev-docs-theme", mode), mode);
    await page.goto(`${base}/docs/motion-drawer/`, { waitUntil: "domcontentloaded" });
    const launcher = page.getByRole("button", { name: "Request a feature or report a bug", exact: true });
    await page.waitForFunction(() => document.querySelector('.report-launcher')?.disabled === false);
    assert.equal(await page.locator('.report-launcher-shape').evaluate(node => getComputedStyle(node).animationName), 'none', 'Reporting has no perpetual decorative idle animation');
    await launcher.hover();
    await page.emulateMedia({ reducedMotion: 'reduce' });
    assert.equal(await page.locator('.report-launcher-shape').evaluate(node => getComputedStyle(node).animationName), 'none', 'Reduced motion suppresses hovered launcher feedback too');
    await page.emulateMedia({ reducedMotion: 'no-preference' });
    await launcher.click();
    const dialog = page.getByRole("dialog", { name: "Request a feature or report a bug", exact: true });
    await dialog.waitFor();
    assert.equal(await dialog.locator('.v-motion-drawer__top:visible').count(), 0, "A stack is one object, not a separate heading panel");
    await dialog.getByRole('heading', { name: 'Request a feature', exact: true }).waitFor();
    const dialogTitleBounds = await dialog.getByRole('heading', { name: 'Request a feature or report a bug', exact: true }).boundingBox();
    assert(dialogTitleBounds && dialogTitleBounds.width <= 1 && dialogTitleBounds.height <= 1, "The generic title names the dialog without painting a heading box");
    assert.equal(await dialog.locator('[data-active="true"] [data-slot="scroll-area-viewport"]').count(), 1, "The active card uses the shared custom scroll surface");
    const scrolling = await dialog.locator('[data-stack-card][data-active="true"]').evaluate(card => {
      const viewport = card.querySelector('[data-slot="scroll-area-viewport"]');
      return { card: card.clientHeight, viewport: viewport.clientHeight, content: viewport.scrollHeight };
    });
    assert(scrolling.viewport > scrolling.card * .7, "The shared viewport fills the card, not a generic 240px cap");
    assert(scrolling.content > scrolling.viewport, "Long report content belongs to the custom viewport");
    assert.equal(await dialog.getByRole("tab").count(), 2, "Reporting uses two discoverable stack selectors");
    const request = dialog.getByRole("tab", { name: "Request a feature", exact: true });
    const bug = dialog.getByRole("tab", { name: "Report a bug", exact: true });
    await dialog.getByLabel("Component title", { exact: true }).fill("A quiet date picker");
    await dialog.getByLabel("Details, inspiration & links", { exact: true }).fill("A reusable date picker with clear date ranges.");
    await dialog.getByLabel("Your email", { exact: true }).fill("local-check@example.com");
    await dialog.getByLabel("Attach images or videos", { exact: true }).setInputFiles(attachment);
    await dialog.getByAltText("Attachment preview: reference.png").waitFor();
    await bug.click();
    await dialog.getByRole('heading', { name: 'Report a bug', exact: true }).waitFor();
    assert.equal(await dialog.getByLabel("What went wrong?", { exact: true }).inputValue(), "", "Bug draft must not inherit request fields");
    assert.equal(await dialog.getByAltText("Attachment preview: reference.png").count(), 0, "Attachments belong to their own draft");
    await dialog.getByLabel("What went wrong?", { exact: true }).fill("A menu closes too quickly");
    await dialog.getByLabel("What happened, and what did you expect?", { exact: true }).fill("Opening a menu should leave enough time to choose.");
    await dialog.getByLabel("Your email", { exact: true }).fill("bug-check@example.com");
    await request.click();
    assert.equal(await dialog.getByLabel("Component title", { exact: true }).inputValue(), "A quiet date picker");
    await dialog.getByAltText("Attachment preview: reference.png").waitFor();
    await dialog.getByRole("button", { name: "Close reporting panel", exact: true }).click();
    await dialog.waitFor({ state: "hidden" });
    await page.reload({ waitUntil: "domcontentloaded" });
    await page.waitForFunction(() => document.querySelector('.report-launcher')?.disabled === false);
    await launcher.click(); await dialog.waitFor();
    assert.equal(await dialog.getByLabel("Component title", { exact: true }).inputValue(), "A quiet date picker", "Request persists across reload");
    await bug.click();
    assert.equal(await dialog.getByLabel("What went wrong?", { exact: true }).inputValue(), "A menu closes too quickly", "Bug persists independently across reload");
    await request.click();
    await dialog.getByRole("button", { name: "Review request", exact: true }).click();
    await dialog.getByRole("heading", { name: "Ready to send?", exact: true }).waitFor();
    assert(await dialog.getByRole("button", { name: "Send request", exact: true }).isDisabled(), "Disconnected service still cannot send");
    await bug.click(); await request.click();
    await dialog.getByRole("heading", { name: "Ready to send?", exact: true }).waitFor();
    await dialog.getByRole("button", { name: "Back to edit", exact: true }).click();
    await page.emulateMedia({ reducedMotion: "reduce" });
    await dialog.getByLabel("Component title", { exact: true }).waitFor();
    const activePanel = dialog.getByRole("tabpanel");
    await activePanel.evaluate(node => { for (const el of [node, ...node.querySelectorAll('*')]) if (el.scrollHeight > el.clientHeight + 20) el.scrollTop = 0; });
    const bounds = await dialog.boundingBox();
    assert(bounds.x >= 0 && bounds.y >= 0 && bounds.x + bounds.width <= width + 1 && bounds.y + bounds.height <= 961);
    assert(await request.isVisible() && await bug.isVisible(), "Both stack labels remain evident");
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: `${out}/request-${width}-${mode}.png` });
    await bug.click();
    await dialog.getByRole("button", { name: "Pin elements", exact: true }).click();
    await page.getByRole("dialog", { name: "Pin elements", exact: true }).waitFor();
    await page.keyboard.press("Escape"); await dialog.waitFor();
    assert.equal(await dialog.getByLabel("What went wrong?", { exact: true }).inputValue(), "A menu closes too quickly");
    await page.screenshot({ path: `${out}/bug-${width}-${mode}.png` });
    await page.keyboard.press("Escape"); await dialog.waitFor({ state: "hidden" });
    assert.deepEqual(errors, []); assert.deepEqual(submissions, []);
    await context.close();
  }
  console.log("PASS: two report cards, independent persisted fields/files/review, mobile/light/dark, pin lifecycle and disconnected-send boundary.");
} finally { await browser.close(); }
