import { GuideShell } from "@/components/landing/guide-shell";
import { AnalyticsPreferences } from "@/components/analytics/analytics-preferences";
import { contactEmail, pageMetadata, site, siteFlags } from "@/lib/site-config";
import "@/components/landing/landing.css";

export const metadata = pageMetadata("Privacy", "How 000h measures website activity, what a bug report or component request carries, and how to choose whether optional analytics is allowed.", "/privacy/");

export default function PrivacyPage() {
  return <GuideShell eyebrow="Your visit, your choice" title="A little clarity." intro="We want to know which components help people, and the report panel is how you tell us directly. Here is what the website measures, what a report carries, and how you can choose or withdraw optional analytics.">
    <section><AnalyticsPreferences /><p>The website sends no optional analytics until you choose Allow analytics. That choice is stored only in this browser under <code>000h.analytics-consent.v1</code>; it is not a visitor identifier. You can withdraw it here at any time. The website also respects Do Not Track and Global Privacy Control signals from your browser.</p></section>
    <section><h2>What helps us improve</h2><p>When connected, optional PostHog analytics records page categories, component previews, interactions with demos, successful command and code copies, and broad categories of outgoing links. Approved campaign labels help us understand which launch channels lead people here. A configured beta or production build also attaches which deployment the event came from and the commit the site was built from, so a measurement can be tied to a specific release; a build without those identifiers sends neither.</p><p>An anonymous identifier exists only in the page’s memory and is replaced on a full reload. We do not use analytics cookies, persistent visitor identifiers, session recordings, advertising profiles or automatic capture of everything you click.</p></section>
    <section><h2>What stays out</h2><p>Analytics does not include typed text, clipboard contents, screenshots, feedback messages, email addresses, full referring URLs or arbitrary search parameters. Administrative and workspace pages are excluded. The request and feedback service is separate: submitting a report sends the information you choose to include.</p><p>PostHog and the hosting provider necessarily receive network information when responding to a request. Our event payloads omit IP addresses and browser user-agent strings, and disable PostHog person profiles and geographic enrichment. This is not a promise that infrastructure providers keep no operational logs.</p></section>
    <section><h2>When you send a report</h2><p>Reporting is separate from analytics. What you write — the text, the email address, the files and any browser details — stays on this device until you submit it. Some network requests do happen before that: opening the panel asks our report service for its settings, and the review step loads Cloudflare’s verification widget. Neither carries your draft. A report needs a subject, a description and an email address to reply to; it will not send without them. Everything else is your choice: files you attach, a screenshot the panel captures for you, elements you point at, links found in your text, and browser details.</p><p>A review step comes before sending. It shows the exact fields, the text and the files that will leave this device, and you can go back and change any of them. Images and video you attach yourself are not inspected or redacted: what is in them is what we receive. The screenshot the panel takes for you is different — it leaves out form controls and regions marked private, as a best effort rather than a guarantee. Either way, treat that step as the last check on what the image shows.</p></section>
    <section><h2>Drafts stay on this device</h2><p>As you write, the panel saves the draft in this browser so closing the panel or reloading does not lose it. The saved draft holds your text, the email address, the complete files you attached, any browser details you included, and the receipt key of a report you already sent. Saving sends nothing, and the draft has no expiry.</p><p>Clear draft empties the one you are looking at; a draft of the other kind, bug or request, is left as it was. To remove everything this site keeps in this browser, including both drafts and their files, clear this site’s data in your browser settings. Worth doing on a shared computer.</p></section>
    <section><h2>Browser details are yours to add</h2><p>A bug report can carry browser details: your device and browser information, recent warnings and errors, requests that failed, and which elements were clicked — the element, never what you typed. Nothing is attached until you choose to include it, and each group is listed so you can remove any of it before sending.</p><p>Those details come from a short running record the page keeps in memory while you browse. It holds a limited number of recent events, and it does not read field values, request contents, headers, cookies or storage. It is gone when the tab closes or reloads, unless you have put it in a draft. Where addresses, keys, tokens and your home folder path can be recognised in that text, they are masked.</p></section>
    <section><h2>Where a report goes</h2><p>A submitted report goes to our private reporting service on Cloudflare. It holds the subject, the description, the reply address, links, pinned elements, the browser details you included and your files. Maintainers read it on a private page.</p><p>Submitting returns your receipt first. Telling anyone about the report is a separate step: delivery jobs are queued with it and run only once delivery has been switched on and that destination is connected, so a report can sit accepted with nothing delivered yet. Your receipt shows the state of each one.</p><p>One of those jobs mirrors the report as a GitHub issue, and it is deliberately thin: a generic title, the report’s reference and a maintainer-only link. Your subject, description, email address, browser details and files are not copied to GitHub. Which repository receives it depends on the deployment: the beta site uses a separate private feedback repository, and only the production site posts into the public source repository. For a component request, the title you suggested reaches the public request board only if a maintainer approves it.</p><p>The service is configured to erase attachments and browser details thirty days after a report is created, and the report text and reply address after a hundred and eighty. That schedule is what the code does; it is not a promise that every copy is gone. The record that a report existed and any mirrored issue sit outside it, and so do our private database backups, which rotate through a small set of slots set to expire within a week, so recently erased text can survive there briefly. One more thing sits outside it: when a report is saved we store a protected code worked out from your email address, so we can count how many different people asked for the same thing without keeping the address beside that count. Erasing the address does not remove the code, and no removal date is set for it. Our own service does not log what you wrote, but Cloudflare, GitHub and the email provider keep their own operational records on their own terms.</p></section>
    <section><h2>Verification, receipt and email</h2><p>Before a report is accepted, a Cloudflare Turnstile check helps protect against automated submissions. It loads Cloudflare’s script into the page, and verifying the result sends your IP address and the report’s reference to Cloudflare. Our own service also sees your IP address when a report arrives. It keeps a protected hash of it rather than the address itself, tied to a ten-minute window, only to limit how many reports one source can send in a row. That entry stops counting when its window ends, and a later cleanup pass removes it.</p><p>An accepted report gives you a receipt you can download. Keep it private: it lets you check that report’s status and finish uploading the files it was submitted with, until the thirty-day attachment window closes. It does not open the report’s contents; reading those needs maintainer access.</p><p>Email notification is one of those queued jobs. Where it is connected, a message about your report is sent through Resend, which receives your address and that message; where it is not, nothing is sent and the report panel says so. This page cannot tell you which is true at the moment you read it — the panel asks the service when you open it. Your address is stored with the report either way, as the route for a reply. Reports are never sent to the analytics service, and the analytics choice above neither blocks nor sends a report.</p></section>
    <section><h2>Installed components</h2><p>The source you install contains no analytics service or calls back to our analytics. Website measurement belongs to the website; your application and its users remain yours.</p><p>A copied command does not tell us whether it was run. A registry file request does not prove a successful installation. We use those counts as separate signals.</p></section>
    <section><h2>Who runs this site</h2><p>The operator of 000h by Cojeev is Sanjay Kumar, based in Madhya Pradesh, India.</p><p>The component library is free: the source is published under the MIT licence, and this website takes no payments. Sanjay also offers paid design and development services separately from the library.</p></section>
    <section><h2>Settings and questions</h2><p>Appearance and motion preferences may be stored locally so the site remembers your choices. External sites, including GitHub, have their own privacy practices.</p><p>You can {siteFlags.contactEnabled ? <>email <a href={`mailto:${contactEmail}`}>{contactEmail}</a> or <a href={site.creatorUrl}>contact Sanjay through GitHub</a></> : <a href={site.creatorUrl}>contact Sanjay through GitHub</a>} with questions about this site, or inspect the implementation in the <a href={site.sourceUrl}>public source</a>.</p></section>
  </GuideShell>;
}
