import { GuideShell } from "@/components/landing/guide-shell";
import { AnalyticsPreferences } from "@/components/analytics/analytics-preferences";
import { contactEmail, pageMetadata, site, siteFlags } from "@/lib/site-config";
import "@/components/landing/landing.css";

export const metadata = pageMetadata("Privacy", "How 000h measures website activity, what it leaves out, and how to turn optional analytics off.", "/privacy/");

export default function PrivacyPage() {
  return <GuideShell eyebrow="Your visit, your choice" title="A little clarity." intro="We want to know which components help people. Here is what the website measures, and how you can turn optional analytics off.">
    <section><AnalyticsPreferences /><p>The website also respects Do Not Track and Global Privacy Control signals from your browser. Your opt-out preference is stored on this browser; it is not a visitor identifier.</p></section>
    <section><h2>What helps us improve</h2><p>When connected, optional PostHog analytics records page categories, component previews, interactions with demos, successful command and code copies, and broad categories of outgoing links. Approved campaign labels help us understand which launch channels lead people here. Each event also carries which deployment it came from (beta or production) and the commit the site was built from, so a measurement can be tied to a specific release.</p><p>An anonymous identifier exists only in the page’s memory and is replaced on a full reload. We do not use analytics cookies, persistent visitor identifiers, session recordings, advertising profiles or automatic capture of everything you click.</p></section>
    <section><h2>What stays out</h2><p>Analytics does not include typed text, clipboard contents, screenshots, feedback messages, email addresses, full referring URLs or arbitrary search parameters. Administrative and workspace pages are excluded. The request and feedback service is separate: submitting a report sends the information you choose to include.</p><p>PostHog and the hosting provider necessarily receive network information when responding to a request. Our event payloads omit IP addresses and browser user-agent strings, and disable PostHog person profiles and geographic enrichment. This is not a promise that infrastructure providers keep no operational logs.</p></section>
    <section><h2>Installed components</h2><p>The source you install contains no analytics service or calls back to our analytics. Website measurement belongs to the website; your application and its users remain yours.</p><p>A copied command does not tell us whether it was run. A registry file request does not prove a successful installation. We use those counts as separate signals.</p></section>
    <section><h2>Settings and questions</h2><p>Appearance and motion preferences may be stored locally so the site remembers your choices. Reporting features can use their own local settings. External sites, including GitHub, have their own privacy practices.</p><p>You can {siteFlags.contactEnabled ? <>email <a href={`mailto:${contactEmail}`}>{contactEmail}</a> or <a href={site.creatorUrl}>contact Sanjay through GitHub</a></> : <a href={site.creatorUrl}>contact Sanjay through GitHub</a>} with questions about this site, or inspect the implementation in the <a href={site.sourceUrl}>public source</a>.</p></section>
  </GuideShell>;
}
