import * as React from 'react';import {createRoot} from 'react-dom/client';import {motion,useMotionValue,useSpring} from 'motion/react';
import {Button} from '@/registry/cojeev/ui/button';import {ShapeMorph} from '@/registry/cojeev/ui/shape';import {AnimatedIcon} from '@/registry/cojeev/ui/animated-icon';import {StoryDemoShell} from './story-demo-shell';
import './utilities.css';import './styles.css';import './story-demos.css';
const minds=[{name:'Creative',shape:'petal-7',tone:'#f0a4cc',icon:'brain',line:'Room for a different possibility.'},{name:'Analytical',shape:'cushion',tone:'#95bae8',icon:'workflow',line:'A little clarity in the complexity.'},{name:'Curious',shape:'clover-soft',tone:'#a8bc75',icon:'network',line:'Always another connection to find.'}] as const;
function Mind({moving}:{moving:boolean}){
 const [mind,setMind]=React.useState(0),[thoughts,setThoughts]=React.useState(0),[character,setCharacter]=React.useState(0);
 const dx=useMotionValue(0),dy=useMotionValue(0),rx=useSpring(dy,{stiffness:55,damping:20}),ry=useSpring(dx,{stiffness:55,damping:20});
 return <main className="mind-main"><div className="mind-heading"><span className="story-kicker">03 / THE CHANGING MIND</span><h1>New mind.<br/><em>Still yours.</em></h1><p>Change the intelligence. Keep the presence.</p></div><div className="specimen-stage" onPointerMove={e=>{if(!moving||e.pointerType==='touch')return;const b=e.currentTarget.getBoundingClientRect();dx.set((e.clientX-b.left-b.width/2)/b.width*22);dy.set(-(e.clientY-b.top-b.height/2)/b.height*18);}} onPointerLeave={()=>{dx.set(0);dy.set(0);}}>
 <motion.div className="specimen-tilt" style={{rotateX:moving?rx:0,rotateY:moving?ry:0}}><div className={`specimen-object character-${character}`} style={{'--mind-tone':minds[mind].tone} as React.CSSProperties}>
 <div className="specimen-glass"/><ShapeMorph className="specimen-boundary" name="pebble-tall" variant="outline"/><ShapeMorph className="specimen-boundary second-boundary" name="pebble-tall" variant="outline"/>
 <div className="specimen-orbit orbit-a"/><div className="specimen-orbit orbit-b"/><div className="specimen-orbit orbit-c"/>
 <div className="specimen-nucleus"><ShapeMorph name={minds[mind].shape}/><AnimatedIcon name={minds[mind].icon} size="lg"/></div>
 {Array.from({length:thoughts},(_,i)=><span key={i} className={`kept-thought thought-${i}`}><ShapeMorph name="pebble-soft"/><span>{i+1}</span></span>)}
 <span className="specimen-glint"/><span className="specimen-grain"/>
 </div></motion.div><span className="specimen-caption">one continuous presence</span><div className="specimen-label label-memory"><span className="annotation-line"/><span>memory<small>{thoughts?`${thoughts} thought${thoughts===1?'':'s'} held`:'waiting for a thought'}</small></span></div><div className="specimen-label label-soul"><span className="annotation-line"/><span>character<small>{character?'Playful':'Gentle'}</small></span></div></div>
 <div className="mind-controls"><div className="mind-selector" role="group" aria-label="Choose the intelligence">{minds.map((m,i)=><Button key={m.name} variant="ghost" data-morph="fill" data-tier="pill" aria-pressed={mind===i} onClick={()=>setMind(i)}><span style={{background:m.tone}}/>{m.name}</Button>)}</div><p className="mind-line" aria-live="polite">{minds[mind].line}</p><div className="continuity-controls"><Button variant="ghost" data-morph="fill" data-tier="pill" disabled={thoughts>=3} onClick={()=>setThoughts(v=>Math.min(3,v+1))}><AnimatedIcon name="brain" size="sm"/>{thoughts>=3?'Three thoughts, held':'Leave a thought'}</Button><Button variant="ghost" data-morph="fill" data-tier="pill" onClick={()=>setCharacter(v=>1-v)}>Character: {character?'Playful':'Gentle'}</Button>{thoughts>0&&<Button variant="ghost" aria-label="Clear demo thoughts" onClick={()=>setThoughts(0)}><AnimatedIcon name="x" size="sm"/></Button>}</div><span className="mind-hint">Leave a thought. Switch minds. It stays.</span></div>
 </main>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><StoryDemoShell kind="mind">{({moving})=><Mind moving={moving}/>}</StoryDemoShell></React.StrictMode>);
