export const categories = [
  "Actions",
  "Forms",
  "Navigation",
  "Feedback",
  "Charts",
  "Data display",
  "Layout",
  "Conversation",
  "Composition",
  "Typography",
  "Subtle backgrounds",
  "Backgrounds",
  "3D",
  "Effects",
  "Visual effects",
  "Motion",
  "Creative",
  "Tools",
];
