/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/registry-host/wrangler.jsonc --include-runtime=false --env-interface=RegistryHostEnv workers/registry-host/worker-configuration.d.ts` (hash: 69e3991b9a3013ee61fc257aba17ea0f)
interface __BaseEnv_RegistryHostEnv {
	ASSETS: Fetcher;
	COJEEV_HOMEPAGE?: Fetcher;
	ENVIRONMENT: "beta" | "production";
	RELEASE: string;
	DEPLOYMENT_ID?: string;
	PHASE?: string;
	MIGRATION_STAGE?: string;
	REGISTRY_GRAPH?: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface BetaEnv {
		ASSETS: Fetcher;
		COJEEV_HOMEPAGE?: Fetcher;
		ENVIRONMENT: "beta";
		RELEASE: string;
		DEPLOYMENT_ID?: string;
		PHASE?: string;
		MIGRATION_STAGE?: string;
		REGISTRY_GRAPH?: string;
	}
	interface ProductionEnv {
		ASSETS: Fetcher;
		COJEEV_HOMEPAGE?: Fetcher;
		ENVIRONMENT: "production";
		RELEASE: string;
		DEPLOYMENT_ID?: string;
		PHASE?: string;
		MIGRATION_STAGE?: string;
		REGISTRY_GRAPH?: string;
	}
	interface Env extends __BaseEnv_RegistryHostEnv {}
}
interface RegistryHostEnv extends __BaseEnv_RegistryHostEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "RELEASE" | "DEPLOYMENT_ID" | "PHASE" | "MIGRATION_STAGE" | "REGISTRY_GRAPH">> {}
}
