/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/registry-host/wrangler.jsonc --include-runtime=false --env-interface=RegistryHostEnv workers/registry-host/worker-configuration.d.ts` (hash: 8b966bf1771ef314fd616ad47b3307dc)
interface __BaseEnv_RegistryHostEnv {
	REGISTRY_METRICS: AnalyticsEngineDataset;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_RegistryHostEnv {}
}
interface RegistryHostEnv extends __BaseEnv_RegistryHostEnv {}
