/**
 * Generated by scripts/generate-specimen-api.mjs — do not edit by hand.
 *
 * The public prop surface of every specimen on the assembly bench, read from
 * `registry/cojeev/ui/<id>.tsx` with the TypeScript compiler. Regenerate with
 * `npm run specimens:api`; tests/component-api.test.ts guards it against drift.
 */

/** One authored prop of an exported props type. */
export type SpecimenApiProp = {
  readonly name: string;
  readonly type: string;
  readonly required: boolean;
  readonly description: string;
};

/** One exported props type of a specimen component. */
export type SpecimenApiDeclaration = {
  readonly name: string;
  readonly props: readonly SpecimenApiProp[];
};

/** Keyed by registry component id, in the order the types are declared. */
export const SPECIMEN_API: Record<string, readonly SpecimenApiDeclaration[]> = {
  "button": [
    {
      "name": "ButtonProps",
      "props": [
        {
          "name": "variant",
          "type": "\"default\" | \"accent\" | \"secondary\" | \"ghost\" | \"outline\" | \"danger\" | \"block\" | null | undefined",
          "required": false,
          "description": ""
        },
        {
          "name": "size",
          "type": "\"default\" | \"sm\" | \"lg\" | null | undefined",
          "required": false,
          "description": ""
        },
        {
          "name": "shape",
          "type": "\"pill\" | \"card\" | null | undefined",
          "required": false,
          "description": ""
        },
        {
          "name": "fullWidth",
          "type": "boolean | null | undefined",
          "required": false,
          "description": ""
        },
        {
          "name": "asChild",
          "type": "boolean",
          "required": false,
          "description": "Use one native element (for example a link) as the interactive root."
        },
        {
          "name": "ref",
          "type": "React.Ref<HTMLButtonElement | HTMLAnchorElement>",
          "required": false,
          "description": ""
        },
        {
          "name": "loading",
          "type": "boolean",
          "required": false,
          "description": ""
        },
        {
          "name": "loadingIndicator",
          "type": "React.ReactNode",
          "required": false,
          "description": ""
        },
        {
          "name": "radius",
          "type": "ControlRadius",
          "required": false,
          "description": ""
        }
      ]
    }
  ],
  "input": [
    {
      "name": "InputProps",
      "props": [
        {
          "name": "variant",
          "type": "\"default\" | \"cream\" | null | undefined",
          "required": false,
          "description": ""
        },
        {
          "name": "size",
          "type": "\"default\" | \"sm\" | null | undefined",
          "required": false,
          "description": ""
        },
        {
          "name": "radius",
          "type": "ControlRadius",
          "required": false,
          "description": ""
        },
        {
          "name": "appearance",
          "type": "FieldAppearance",
          "required": false,
          "description": ""
        },
        {
          "name": "nativeSize",
          "type": "number",
          "required": false,
          "description": ""
        }
      ]
    },
    {
      "name": "InputWrapperProps",
      "props": [
        {
          "name": "variant",
          "type": "\"default\" | \"cream\" | null | undefined",
          "required": false,
          "description": ""
        },
        {
          "name": "size",
          "type": "\"default\" | \"sm\" | null | undefined",
          "required": false,
          "description": ""
        },
        {
          "name": "radius",
          "type": "ControlRadius",
          "required": false,
          "description": ""
        },
        {
          "name": "appearance",
          "type": "FieldAppearance",
          "required": false,
          "description": ""
        },
        {
          "name": "ref",
          "type": "React.Ref<HTMLElement>",
          "required": false,
          "description": ""
        },
        {
          "name": "as",
          "type": "\"div\" | \"label\"",
          "required": false,
          "description": ""
        }
      ]
    },
    {
      "name": "InputControlProps",
      "props": []
    },
    {
      "name": "InputAddonProps",
      "props": []
    },
    {
      "name": "InputAffixProps",
      "props": []
    },
    {
      "name": "InputClearProps",
      "props": [
        {
          "name": "onClear",
          "type": "() => void",
          "required": false,
          "description": ""
        }
      ]
    }
  ],
  "switch": [
    {
      "name": "SwitchProps",
      "props": [
        {
          "name": "appearance",
          "type": "\"capsule\" | \"rocker\" | \"latch\"",
          "required": false,
          "description": ""
        },
        {
          "name": "radius",
          "type": "ControlRadius",
          "required": false,
          "description": ""
        }
      ]
    },
    {
      "name": "SwitchRowProps",
      "props": []
    }
  ],
  "checkbox": [
    {
      "name": "CheckboxProps",
      "props": [
        {
          "name": "appearance",
          "type": "\"row\" | \"card\" | \"chip\"",
          "required": false,
          "description": ""
        },
        {
          "name": "radius",
          "type": "ControlRadius",
          "required": false,
          "description": ""
        },
        {
          "name": "shape",
          "type": "SelectorShape",
          "required": false,
          "description": ""
        },
        {
          "name": "tone",
          "type": "SelectorTone",
          "required": false,
          "description": ""
        },
        {
          "name": "size",
          "type": "SelectorSize",
          "required": false,
          "description": ""
        },
        {
          "name": "indicator",
          "type": "SelectorIndicator",
          "required": false,
          "description": ""
        },
        {
          "name": "showIndicator",
          "type": "boolean",
          "required": false,
          "description": ""
        }
      ]
    },
    {
      "name": "CheckboxGroupProps",
      "props": []
    },
    {
      "name": "CheckboxBodyProps",
      "props": []
    }
  ],
  "slider": [
    {
      "name": "SliderProps",
      "props": [
        {
          "name": "variant",
          "type": "\"default\" | \"pink\" | null | undefined",
          "required": false,
          "description": ""
        },
        {
          "name": "thumbLabel",
          "type": "string|((index:number)=>string)",
          "required": false,
          "description": ""
        },
        {
          "name": "appearance",
          "type": "SliderAppearance",
          "required": false,
          "description": ""
        }
      ]
    },
    {
      "name": "SliderWrapperProps",
      "props": []
    },
    {
      "name": "SliderRowProps",
      "props": []
    },
    {
      "name": "SliderOutputProps",
      "props": []
    }
  ],
  "badge": [
    {
      "name": "BadgeProps",
      "props": [
        {
          "name": "variant",
          "type": "\"default\" | \"danger\" | \"cream\" | \"pink\" | \"yellow\" | \"olive\" | \"blue\" | \"ink\" | \"pink-soft\" | \"yellow-soft\" | \"olive-soft\" | \"blue-soft\" | \"pending\" | \"count\" | \"dashed\" | \"caps\" | \"test\" | \"live\" | null | undefined",
          "required": false,
          "description": ""
        },
        {
          "name": "size",
          "type": "\"default\" | \"sm\" | \"lg\" | null | undefined",
          "required": false,
          "description": ""
        },
        {
          "name": "appearance",
          "type": "\"stamp\" | \"tag\" | \"counter\"",
          "required": false,
          "description": ""
        },
        {
          "name": "radius",
          "type": "ControlRadius",
          "required": false,
          "description": ""
        }
      ]
    }
  ],
  "kbd": [
    {
      "name": "KbdProps",
      "props": [
        {
          "name": "variant",
          "type": "\"default\" | null | undefined",
          "required": false,
          "description": ""
        },
        {
          "name": "size",
          "type": "\"default\" | null | undefined",
          "required": false,
          "description": ""
        },
        {
          "name": "as",
          "type": "React.ElementType",
          "required": false,
          "description": ""
        }
      ]
    }
  ],
  "progress": [
    {
      "name": "ProgressProps",
      "props": [
        {
          "name": "variant",
          "type": "\"default\" | \"cream\" | \"unavail\" | null | undefined",
          "required": false,
          "description": ""
        },
        {
          "name": "size",
          "type": "\"default\" | \"sm\" | \"lg\" | null | undefined",
          "required": false,
          "description": ""
        },
        {
          "name": "value",
          "type": "number|null",
          "required": false,
          "description": ""
        },
        {
          "name": "max",
          "type": "number",
          "required": false,
          "description": ""
        },
        {
          "name": "appearance",
          "type": "ProgressAppearance",
          "required": false,
          "description": ""
        },
        {
          "name": "segments",
          "type": "number",
          "required": false,
          "description": ""
        }
      ]
    },
    {
      "name": "ProgressIndicatorProps",
      "props": []
    }
  ],
  "spinner": [
    {
      "name": "SpinnerProps",
      "props": [
        {
          "name": "variant",
          "type": "\"default\" | \"point\" | null | undefined",
          "required": false,
          "description": ""
        },
        {
          "name": "size",
          "type": "\"default\" | null | undefined",
          "required": false,
          "description": ""
        },
        {
          "name": "label",
          "type": "string",
          "required": false,
          "description": ""
        },
        {
          "name": "appearance",
          "type": "SpinnerAppearance",
          "required": false,
          "description": ""
        },
        {
          "name": "paused",
          "type": "boolean",
          "required": false,
          "description": ""
        }
      ]
    },
    {
      "name": "SpinnerLabelProps",
      "props": [
        {
          "name": "variant",
          "type": "\"default\" | null | undefined",
          "required": false,
          "description": ""
        },
        {
          "name": "size",
          "type": "\"default\" | null | undefined",
          "required": false,
          "description": ""
        }
      ]
    }
  ],
  "animated-icon": [
    {
      "name": "AnimatedIconProps",
      "props": [
        {
          "name": "amplitude",
          "type": "number | string | undefined",
          "required": false,
          "description": ""
        },
        {
          "name": "preset",
          "type": "IconMotion",
          "required": false,
          "description": ""
        },
        {
          "name": "active",
          "type": "boolean",
          "required": false,
          "description": ""
        },
        {
          "name": "duration",
          "type": "number",
          "required": false,
          "description": ""
        },
        {
          "name": "ease",
          "type": "IconMotionEase",
          "required": false,
          "description": ""
        }
      ]
    },
    {
      "name": "StateChevronProps",
      "props": [
        {
          "name": "open",
          "type": "boolean",
          "required": false,
          "description": "Omit to follow the closest native trigger's data-state/aria-expanded."
        },
        {
          "name": "direction",
          "type": "\"down\" | \"right\"",
          "required": false,
          "description": ""
        }
      ]
    }
  ],
  "shape-artwork": [
    {
      "name": "ShapeArtworkProps",
      "props": [
        {
          "name": "name",
          "type": "SignatureShapeName",
          "required": false,
          "description": ""
        },
        {
          "name": "tone",
          "type": "ShapeArtworkTone",
          "required": false,
          "description": ""
        },
        {
          "name": "rotation",
          "type": "number",
          "required": false,
          "description": "Foreground rotation, in degrees."
        },
        {
          "name": "filled",
          "type": "boolean",
          "required": false,
          "description": "False draws the foreground as an outline."
        },
        {
          "name": "shadow",
          "type": "boolean",
          "required": false,
          "description": ""
        },
        {
          "name": "shadowAngle",
          "type": "number",
          "required": false,
          "description": "Direction of the cast shadow, clockwise from the right."
        },
        {
          "name": "echo",
          "type": "boolean",
          "required": false,
          "description": ""
        },
        {
          "name": "echoAngle",
          "type": "number",
          "required": false,
          "description": "Rear outline rotation relative to the foreground."
        },
        {
          "name": "label",
          "type": "string",
          "required": false,
          "description": "Omit when decorative."
        },
        {
          "name": "ambient",
          "type": "boolean",
          "required": false,
          "description": "Opt-in ambient contour motion. It pauses offscreen and in quiet motion modes."
        },
        {
          "name": "morphTo",
          "type": "SignatureShapeName",
          "required": false,
          "description": "Compatible signature silhouette used as the far end of the living contour."
        },
        {
          "name": "morphDuration",
          "type": "number",
          "required": false,
          "description": "Full breathe cycle in seconds."
        },
        {
          "name": "motionDelay",
          "type": "number",
          "required": false,
          "description": "Staggers compositions without relying on render-time randomness."
        }
      ]
    }
  ],
  "pattern-background": [
    {
      "name": "PatternBackgroundProps",
      "props": [
        {
          "name": "color",
          "type": "string | undefined",
          "required": false,
          "description": ""
        },
        {
          "name": "variant",
          "type": "PatternBackgroundVariant",
          "required": false,
          "description": ""
        },
        {
          "name": "spacing",
          "type": "number",
          "required": false,
          "description": "Distance between marks, in pixels (8–80)."
        },
        {
          "name": "opacity",
          "type": "number",
          "required": false,
          "description": "Decorative ink strength, from 0 to 1."
        }
      ]
    }
  ]
};
