import fs from 'node:fs';
import {chromium} from 'playwright';
import {preview} from 'vite';
import {factoryCfg,factoryTiers,FLOW_CHARACTERS,FLOW_INTENSITY} from '../registry/cojeev/motion/settings.ts';
const server=process.argv.includes('--serve')?await preview({configFile:false,base:'/cojeev-ui/',build:{outDir:'out'},preview:{host:'127.0.0.1',port:0,strictPort:true}}):null;
const out='artifacts/production-motion',base=process.env.POLISH_URL??`http://127.0.0.1:${server?server.httpServer.address().port:4320}/cojeev-ui`;fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch();const rows=[],checks=[];
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/docs/tabs/');await page.evaluate(()=>document.fonts.ready);await page.getByRole('button',{name:'Motion settings',exact:true}).first().click();
 const dialog=page.getByRole('dialog'),group=dialog.getByRole('tablist',{name:'Motion preview'}),tabs=group.getByRole('tab');await group.waitFor();await page.waitForTimeout(400);
 for(const [id,preset] of Object.entries(FLOW_CHARACTERS).filter(([id])=>id!=='off')){
  await dialog.getByRole('button',{name:preset.label,exact:true}).click();await page.waitForTimeout(90);
  await group.evaluate(g=>{window.__preset={g,frames:[],stop:false};const r=window.__preset;function frame(t){if(r.stop)return;const p=g.querySelector(':scope>.v-glide__pill'),s=p&&getComputedStyle(p);r.frames.push({t,x:s?.transform,w:s?.width,h:s?.height,phase:p?.className,animation:p?.firstElementChild&&getComputedStyle(p.firstElementChild).animationName,after:p?.firstElementChild&&getComputedStyle(p.firstElementChild,'::after').animationName});requestAnimationFrame(frame)}requestAnimationFrame(frame)});
  await tabs.nth(2).click();await page.waitForTimeout(75);await tabs.nth(1).click();await page.waitForTimeout(65);await tabs.nth(0).click();await page.waitForTimeout(1350);
  const result=await group.evaluate(g=>{const r=window.__preset;r.stop=true;const selected=g.querySelector('[aria-selected=true]'),p=g.querySelector(':scope>.v-glide__pill'),a=selected.getBoundingClientRect(),b=p.getBoundingClientRect();return{variant:g.dataset.flowV,active:selected.textContent,error:{x:b.x-a.x,y:b.y-a.y,w:b.width-a.width,h:b.height-a.height},layers:['pill','hover','trail'].map(k=>g.querySelectorAll(':scope>.v-glide__'+k).length),hostTransforms:[...g.querySelectorAll('[role=tab]')].map(e=>getComputedStyle(e).transform),running:document.getAnimations().filter(a=>a.playState==='running'&&g.contains(a.effect?.target)).length,phase:p.className,frames:r.frames,stored:JSON.parse(localStorage.getItem('v-flow-v1'))}});
  const pass=result.variant===id&&result.active==='Overview'&&Math.max(...Object.values(result.error).map(Math.abs))<.04&&result.layers.every(n=>n===1)&&result.hostTransforms.every(x=>x==='none')&&result.running===0&&!/-phase1|-gather|-shoot|-lead|-land/.test(result.phase)&&result.stored.variant===id;
  rows.push({id,pass,...result});console.log(JSON.stringify({id,pass,error:result.error,running:result.running}));
 }
 // A Speed step changes root custom properties, so one whole-document style pass is inherent.
 // Each further pass is a JS read forced after those writes; every one adds a stall to the slider.
 const cdp=await context.newCDPSession(page),documentPasses=async act=>{const total=await page.evaluate(()=>document.getElementsByTagName('*').length);await cdp.send('Tracing.start',{categories:'devtools.timeline,disabled-by-default-devtools.timeline.stack',transferMode:'ReturnAsStream'});await act();await page.waitForTimeout(250);const done=new Promise(resolve=>cdp.once('Tracing.tracingComplete',resolve));await cdp.send('Tracing.end');const {stream}=await done;let data='';for(;;){const chunk=await cdp.send('IO.read',{handle:stream});data+=chunk.data;if(chunk.eof)break}await cdp.send('IO.close',{handle:stream});const trace=JSON.parse(data);return (trace.traceEvents??trace).filter(e=>e.name==='UpdateLayoutTree'&&e.args?.beginData?.stackTrace&&(e.args.elementCount??0)>=total/2).length};
 const speed=dialog.getByRole('slider',{name:'Motion speed'}),intensity=dialog.getByRole('slider',{name:'Motion intensity'});await speed.focus();const passes=await documentPasses(()=>page.keyboard.press('ArrowRight'));checks.push({name:'a Speed step forces at most one whole-document style pass',pass:passes<=1,passes});await intensity.focus();await page.keyboard.press('ArrowRight');
 const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('v-flow-v1')));checks.push({name:'speed and intensity controls persist independently of preset',pass:stored.variant==='halo'&&stored.speed>1&&stored.intensity>1,stored});
 await page.reload();await page.getByRole('button',{name:'Motion settings',exact:true}).first().click();checks.push({name:'preset and tuning survive page reload',pass:await page.getByRole('dialog').getByRole('button',{name:'Halo',exact:true}).getAttribute('aria-pressed')==='true',stored:await page.evaluate(()=>JSON.parse(localStorage.getItem('v-flow-v1')))});
 checks.push({name:'no runtime errors',pass:errors.length===0,errors});await context.close();
 const c=await browser.newContext({viewport:{width:1440,height:1000}});await c.addInitScript(({factoryCfg,factoryTiers})=>{localStorage.setItem('v-morph-cfg-v3',JSON.stringify({cfg:factoryCfg,TIER:factoryTiers}));},{factoryCfg,factoryTiers});const p=await c.newPage();await p.goto(base+'/docs/pagination/');await p.evaluate(()=>document.fonts.ready);const pager=p.locator('[data-example-role="interactive"] [data-slot="pagination"]').first();await pager.waitFor();await pager.scrollIntoViewIfNeeded();await p.waitForTimeout(1800);const target=pager.getByRole('button',{name:'Page 2',exact:true});
 const snapshot=()=>target.evaluate(e=>{const r=e.getBoundingClientRect();return {transform:getComputedStyle(e).transform,box:{x:r.x,y:r.y,w:r.width,h:r.height},bodies:e.querySelectorAll(':scope>svg.v-morph').length,hit:document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest('button')===e}});const rest=await snapshot();await target.hover();await p.mouse.down();await p.waitForTimeout(250);const held=await snapshot();await p.waitForTimeout(250);const heldLater=await snapshot();await p.mouse.up();await p.mouse.move(0,950);await p.waitForTimeout(500);const released=await snapshot();const samples=[rest,held,heldLater,released];checks.push({name:'Pagination keeps one animated paint owner and steady native targets through selection',pass:samples.every(s=>s.bodies===1&&s.transform==='none'&&s.hit&&Object.keys(rest.box).every(k=>Math.abs(s.box[k]-rest.box[k])<1))&&await pager.getAttribute('data-page')==='2'&&await pager.locator('[aria-current="page"]').count()===1,rest,held,heldLater,released});await c.close();
 const off=await browser.newContext({viewport:{width:1440,height:1000}});await off.addInitScript(()=>localStorage.setItem('v-motion',JSON.stringify({v:3,mode:'off',cats:{buttons:true}})));const op=await off.newPage();await op.goto(base+'/docs/button/');await op.evaluate(()=>document.fonts.ready);const button=op.locator('.v-preview__canvas .v-btn').first();await button.waitFor();await button.scrollIntoViewIfNeeded();await button.hover();await op.mouse.down();const pressed=await button.evaluate(e=>({transform:getComputedStyle(e).transform,translate:getComputedStyle(e).translate,duration:getComputedStyle(e).transitionDuration,body:e.querySelectorAll(':scope>svg.v-morph').length}));await op.mouse.up();checks.push({name:'Off disables native Button press movement after Morph detaches',pass:pressed.transform==='none'&&['none','0px','0px 0px'].includes(pressed.translate)&&pressed.body===0,pressed});await off.close();
 // The sheet preview can pass while real pages ignore it: choose in the sheet, close it, then move a docs example.
 const live=await browser.newContext({viewport:{width:1440,height:1000}}),lp=await live.newPage();await lp.goto(base+'/docs/tabs/');await lp.evaluate(()=>document.fonts.ready);
 const example=lp.locator('[data-example-role="interactive"] [data-flow-owned].v-glide[role=tablist]').first(),exampleTabs=example.getByRole('tab');await example.waitFor();
 const choose=async(label,keys={},reset=false)=>{await lp.getByRole('button',{name:'Motion settings',exact:true}).first().click();const sheet=lp.getByRole('dialog');if(reset)await sheet.getByRole('button',{name:'Reset motion settings',exact:true}).click();await sheet.getByRole('button',{name:label,exact:true}).click();for(const [name,key] of Object.entries(keys)){await sheet.getByRole('slider',{name}).focus();await lp.keyboard.press(key)}await lp.keyboard.press('Escape');await sheet.waitFor({state:'hidden'})};
 const travel=async(settle=1600)=>{await example.scrollIntoViewIfNeeded();await exampleTabs.first().click();await lp.mouse.move(0,0);await lp.waitForTimeout(settle);
  await example.evaluate(g=>{const r=window.__travel={frames:[],stop:false};const frame=t=>{if(r.stop)return;const pill=g.querySelector(':scope>.v-glide__pill'),body=pill.firstElementChild,b=pill.getBoundingClientRect(),scale=/scaleX\(([-\d.]+)\)/.exec(body?.style.transform??'');r.frames.push({t,x:b.x,w:b.width,phase:pill.className,land:scale?Math.abs(+scale[1]-1):0,aura:body?.childElementCount??0,auraScale:body?.lastElementChild?body.lastElementChild.getBoundingClientRect().width/body.getBoundingClientRect().width:0});requestAnimationFrame(frame)};requestAnimationFrame(frame)});
  await exampleTabs.nth(2).click();await lp.mouse.move(0,0);await lp.waitForTimeout(settle);
  const {variant,frames}=await example.evaluate(g=>{window.__travel.stop=true;return {variant:g.dataset.flowV,frames:window.__travel.frames}});
  const moving=frames.filter((f,i)=>i&&(Math.abs(f.x-frames[i-1].x)>.3||Math.abs(f.w-frames[i-1].w)>.3));
  return {variant,travelMs:moving.length?Math.round(moving.at(-1).t-moving[0].t):0,distance:Math.round(Math.abs(frames.at(-1).x-frames[0].x)),widest:+(Math.max(...frames.map(f=>f.w))-Math.max(frames[0].w,frames.at(-1).w)).toFixed(1),narrowest:+Math.min(...frames.map(f=>f.w)).toFixed(1),land:+Math.max(...frames.map(f=>f.land)).toFixed(3),aura:Math.max(...frames.map(f=>f.aura)),auraScale:+Math.max(...frames.map(f=>f.auraScale)).toFixed(2),phases:[...new Set(frames.flatMap(f=>f.phase.split(/\s+/)).filter(c=>c.startsWith('-')))]}};
 const traits={glide:m=>m.widest<1&&m.land===0&&!m.phases.length,stretch:m=>m.phases.includes('-phase1')&&m.widest>20,jelly:m=>m.land>=.1,comet:m=>m.land>0,drop:m=>m.phases.includes('-gather')&&m.phases.includes('-shoot')&&m.narrowest<24,rubber:m=>m.phases.includes('-lead'),pebble:m=>m.land>0,ripple:m=>m.aura>0,halo:m=>m.aura>0};
 for(const [id,preset] of Object.entries(FLOW_CHARACTERS).filter(([id])=>id!=='off')){await choose(preset.label);const m=await travel();checks.push({name:`${preset.label} moves a real docs example with its own character`,pass:m.variant===id&&m.distance>40&&m.travelMs>60&&traits[id](m),...m})}
 await choose('Stretch',{'Motion speed':'Home'});const slow=await travel(2800);await choose('Stretch',{'Motion speed':'End'});const fast=await travel();
 checks.push({name:'Speed measurably changes travel on a real docs example',pass:slow.travelMs>2.5*fast.travelMs&&fast.travelMs>0,slow:slow.travelMs,fast:fast.travelMs});
 // Intensity is live only where it changes what the person sees; elsewhere the slider is disabled and says why.
 const intensityNote=async label=>{await lp.getByRole('button',{name:'Motion settings',exact:true}).first().click();const sheet=lp.getByRole('dialog');await sheet.getByRole('button',{name:label,exact:true}).click();const slider=await sheet.getByRole('slider',{name:'Motion intensity'}).evaluate(e=>({disabled:e.hasAttribute('data-disabled'),note:document.getElementById(e.getAttribute('aria-describedby')??'')?.textContent??''}));await lp.keyboard.press('Escape');await sheet.waitFor({state:'hidden'});return slider};
 const intensityShows={jelly:(calm,lively)=>lively.land-calm.land>=.2,pebble:(calm,lively)=>lively.land-calm.land>=.1,ripple:(calm,lively)=>calm.aura===0&&lively.aura>0&&lively.auraScale>=1.4,halo:(calm,lively)=>calm.aura===0&&lively.aura>0&&lively.auraScale>=1.4};
 for(const [id,preset] of Object.entries(FLOW_CHARACTERS).filter(([id])=>id!=='off')){
  const slider=await intensityNote(preset.label);
  if(!FLOW_INTENSITY.has(id)){checks.push({name:`${preset.label} disables Intensity and says why`,pass:slider.disabled&&/Intensity is off\.$/.test(slider.note),...slider});continue}
  await choose(preset.label,{'Motion intensity':'Home'},true);const calm=await travel();await choose(preset.label,{'Motion intensity':'End'});const lively=await travel();
  checks.push({name:`Intensity visibly changes ${preset.label} on a real docs example`,pass:!slider.disabled&&slider.note.length>0&&intensityShows[id](calm,lively),note:slider.note,calm:{land:calm.land,aura:calm.aura,auraScale:calm.auraScale},lively:{land:lively.land,aura:lively.aura,auraScale:lively.auraScale}});
 }
 await live.close();
}finally{await browser.close();if(server)await new Promise(resolve=>server.httpServer.close(resolve));fs.writeFileSync(out+'/results.json',JSON.stringify({scope:'Real updated docs MotionControls selects all nine public presets and exercises native fast reversal; persisted tuning, style passes per Speed step, each preset, Speed and per-character Intensity on a real docs example, authored Pagination press and native Button Off checks.',rows,checks},null,2)+'\n');if(rows.some(r=>!r.pass)||checks.some(c=>!c.pass))process.exitCode=1;console.log(JSON.stringify({presets:rows.length,passed:rows.filter(r=>r.pass).length,checks},null,2))}
