import fs from 'node:fs';
import {chromium} from 'playwright';
import {preview} from 'vite';
import {factoryCfg,factoryTiers,FLOW_CHARACTERS} from '../registry/sahajiv/motion/settings.ts';
const server=process.argv.includes('--serve')?await preview({configFile:false,base:'/sahajiv-ui/',build:{outDir:'out'},preview:{host:'127.0.0.1',port:0,strictPort:true}}):null;
const out='artifacts/production-motion',base=process.env.POLISH_URL??`http://127.0.0.1:${server?server.httpServer.address().port:4320}/sahajiv-ui`;fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch();const rows=[],checks=[];
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/docs/tabs/');await page.evaluate(()=>document.fonts.ready);await page.getByRole('button',{name:'Motion settings',exact:true}).first().click();
 const dialog=page.getByRole('dialog'),group=dialog.getByRole('tablist',{name:'Motion preview'}),tabs=group.getByRole('tab');await group.waitFor();await page.waitForTimeout(400);
 for(const [id,preset] of Object.entries(FLOW_CHARACTERS).filter(([id])=>id!=='off')){
  await dialog.getByRole('button',{name:preset.label,exact:true}).click();await page.waitForTimeout(90);
  await group.evaluate(g=>{window.__preset={g,frames:[],stop:false};const r=window.__preset;function frame(t){if(r.stop)return;const p=g.querySelector(':scope>.v-glide__pill'),s=p&&getComputedStyle(p);r.frames.push({t,x:s?.transform,w:s?.width,h:s?.height,phase:p?.className,animation:p?.firstElementChild&&getComputedStyle(p.firstElementChild).animationName,after:p?.firstElementChild&&getComputedStyle(p.firstElementChild,'::after').animationName});requestAnimationFrame(frame)}requestAnimationFrame(frame)});
  await tabs.nth(2).click();await page.waitForTimeout(75);await tabs.nth(1).click();await page.waitForTimeout(65);await tabs.nth(0).click();await page.waitForTimeout(1350);
  const result=await group.evaluate(g=>{const r=window.__preset;r.stop=true;const selected=g.querySelector('[aria-selected=true]'),p=g.querySelector(':scope>.v-glide__pill'),a=selected.getBoundingClientRect(),b=p.getBoundingClientRect();return{variant:g.dataset.flowV,active:selected.textContent,error:{x:b.x-a.x,y:b.y-a.y,w:b.width-a.width,h:b.height-a.height},layers:['pill','hover','trail'].map(k=>g.querySelectorAll(':scope>.v-glide__'+k).length),hostTransforms:[...g.querySelectorAll('[role=tab]')].map(e=>getComputedStyle(e).transform),running:document.getAnimations().filter(a=>a.playState==='running'&&g.contains(a.effect?.target)).length,phase:p.className,frames:r.frames,stored:JSON.parse(localStorage.getItem('v-flow-v1'))}});
  const pass=result.variant===id&&result.active==='Overview'&&Math.max(...Object.values(result.error).map(Math.abs))<.04&&result.layers.every(n=>n===1)&&result.hostTransforms.every(x=>x==='none')&&result.running===0&&!/-phase1|-gather|-shoot|-lead|-land/.test(result.phase)&&result.stored.variant===id;
  rows.push({id,pass,...result});console.log(JSON.stringify({id,pass,error:result.error,running:result.running}));
 }
 const speed=dialog.getByRole('slider',{name:'Motion speed'}),intensity=dialog.getByRole('slider',{name:'Motion intensity'});await speed.focus();await page.keyboard.press('ArrowRight');await intensity.focus();await page.keyboard.press('ArrowRight');
 const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('v-flow-v1')));checks.push({name:'speed and intensity controls persist independently of preset',pass:stored.variant==='halo'&&stored.speed>1&&stored.intensity>1,stored});
 await page.reload();await page.getByRole('button',{name:'Motion settings',exact:true}).first().click();checks.push({name:'preset and tuning survive page reload',pass:await page.getByRole('dialog').getByRole('button',{name:'Halo',exact:true}).getAttribute('aria-pressed')==='true',stored:await page.evaluate(()=>JSON.parse(localStorage.getItem('v-flow-v1')))});
 checks.push({name:'no runtime errors',pass:errors.length===0,errors});await context.close();
 const c=await browser.newContext({viewport:{width:1440,height:1000}});await c.addInitScript(({factoryCfg,factoryTiers})=>{localStorage.setItem('v-morph-cfg-v3',JSON.stringify({cfg:factoryCfg,TIER:factoryTiers}));},{factoryCfg,factoryTiers});const p=await c.newPage();await p.goto(base+'/docs/pagination/');await p.evaluate(()=>document.fonts.ready);const pager=p.locator('.v-pager[data-flow-owned]').first();await pager.waitFor();await pager.scrollIntoViewIfNeeded();await p.waitForTimeout(1800);const target=pager.getByRole('button',{name:'2',exact:true});
 const snapshot=()=>target.evaluate(e=>({transform:getComputedStyle(e).transform,path:e.querySelector(':scope>svg.v-morph [data-morph-body]')?.getAttribute('d'),bodies:e.querySelectorAll(':scope>svg.v-morph').length}));const rest=await snapshot();await target.hover();await p.mouse.down();await p.waitForTimeout(250);const held=await snapshot();await p.waitForTimeout(250);const heldLater=await snapshot();await p.mouse.up();await p.mouse.move(0,950);await p.waitForTimeout(500);const released=await snapshot();checks.push({name:'authored Pagination bodies remain still during pointer hold',pass:rest.bodies===1&&rest.transform==='none'&&held.transform==='none'&&held.path===heldLater.path&&held.path===rest.path,rest,held,heldLater,released});await c.close();
 const off=await browser.newContext({viewport:{width:1440,height:1000}});await off.addInitScript(()=>localStorage.setItem('v-motion',JSON.stringify({v:3,mode:'off',cats:{buttons:true}})));const op=await off.newPage();await op.goto(base+'/docs/button/');await op.evaluate(()=>document.fonts.ready);const button=op.locator('.v-preview__canvas .v-btn').first();await button.waitFor();await button.scrollIntoViewIfNeeded();await button.hover();await op.mouse.down();const pressed=await button.evaluate(e=>({transform:getComputedStyle(e).transform,translate:getComputedStyle(e).translate,duration:getComputedStyle(e).transitionDuration,body:e.querySelectorAll(':scope>svg.v-morph').length}));await op.mouse.up();checks.push({name:'Off disables native Button press movement after Morph detaches',pass:pressed.transform==='none'&&['none','0px','0px 0px'].includes(pressed.translate)&&pressed.body===0,pressed});await off.close();
}finally{await browser.close();if(server)await new Promise(resolve=>server.httpServer.close(resolve));fs.writeFileSync(out+'/results.json',JSON.stringify({scope:'Real updated docs MotionControls selects all nine public presets and exercises native fast reversal; persisted tuning, authored Pagination press and native Button Off checks.',rows,checks},null,2)+'\n');if(rows.some(r=>!r.pass)||checks.some(c=>!c.pass))process.exitCode=1;console.log(JSON.stringify({presets:rows.length,passed:rows.filter(r=>r.pass).length,checks},null,2))}
