"""Build page font subsets from the registry's original variable WOFF2 files.

Run with fonttools[woff]==4.65.0. All original characters remain available;
only the commonly used range is preloaded. All variable axes remain unchanged.
"""
from pathlib import Path
from io import BytesIO
import base64
import re
import string
from fontTools import subset
from fontTools.ttLib import TTFont

APP = Path(__file__).resolve().parents[1]
SOURCE = APP.parents[1] / 'registry/cojeev/styles/fonts.css'
OUT = APP / 'src/fonts'
OUT.mkdir(exist_ok=True)
COMMON = set(range(0x20, 0x7f)) | {
    0xa0, 0xb7, 0x2013, 0x2014, 0x2018, 0x2019, 0x201c, 0x201d, 0x2022,
    0x2026, 0x203a, 0x2190, 0x2191, 0x2192, 0x2193, 0x21b5, 0x2212,
}

def ranges(points):
    runs = []
    for point in sorted(points):
        if runs and point == runs[-1][1] + 1:
            runs[-1][1] = point
        else:
            runs.append([point, point])
    return ','.join(f'U+{a:X}' if a == b else f'U+{a:X}-{b:X}' for a, b in runs)

css = ['/* Generated by scripts/prepare-fonts.py; registry glyphs and all original variable axes. */',
       '@layer theme, base, components, utilities, cojeev-states, cojeev-flow, cojeev-morph, cojeev-accessibility;']
for family, encoded in re.findall(r'font-family:"([^"]+)";src:url\("data:font/woff2;base64,([^"]+)', SOURCE.read_text()):
    raw = base64.b64decode(encoded)
    original = TTFont(BytesIO(raw), recalcTimestamp=False)
    cmap = original.getBestCmap()
    axes = [(a.axisTag, a.minValue, a.defaultValue, a.maxValue) for a in original['fvar'].axes]
    slug = family.lower().replace(' ', '-')
    (OUT / f'{slug}-full.woff2').write_bytes(raw)
    # The display face carries prose, initials and the clock; code symbols
    # are used by DM Sans in the prompt. Keep all display letters and digits,
    # and load the untouched full face for uncommon symbols.
    display = set(map(ord, string.ascii_letters + string.digits + " .,:;!?\"'’-–—…\u00a0"))
    common = set(cmap) & (display if family == 'Bricolage Grotesque' else COMMON)
    font = TTFont(BytesIO(raw), recalcTimestamp=False)
    options = subset.Options()
    options.layout_features = ['ccmp','locl','kern','liga','clig','calt','mark','mkmk','rvrn','tnum','lnum','pnum']
    options.name_IDs = ['*']
    options.name_legacy = True
    options.name_languages = ['*']
    sub = subset.Subsetter(options=options)
    sub.populate(unicodes=common)
    sub.subset(font)
    font.save(OUT / f'{slug}-common.woff2')
    assert [(a.axisTag, a.minValue, a.defaultValue, a.maxValue) for a in font['fvar'].axes] == axes
    for cp in common:
        assert original['hmtx'][cmap[cp]] == font['hmtx'][font.getBestCmap()[cp]]
    weight = '200 800' if family == 'Bricolage Grotesque' else '100 1000'
    stretch = 'font-stretch:75% 100%;' if family == 'Bricolage Grotesque' else ''
    for suffix, points in [('full', set(cmap) - common), ('common', common)]:
        css.append(f'@font-face{{font-family:"{family}";src:url("./fonts/{slug}-{suffix}.woff2") format("woff2");font-weight:{weight};font-style:normal;{stretch}font-display:swap;unicode-range:{ranges(points)}}}')
    print(slug, 'common bytes', (OUT / f'{slug}-common.woff2').stat().st_size, 'axes', [(a.axisTag, a.minValue, a.maxValue) for a in font['fvar'].axes])
(APP / 'src/fonts.css').write_text('\n'.join(css) + '\n')
